name: manufacturing_flow_demo
description: Demo mobile app for machine production tracking and dispatch management.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
